### ISSUE TITLE
App rejection due to use of AMBlurView

### ISSUE THREAD

**Issue by tspinelli** [MatthewYork/MYBlurIntroductionView#14]
Apple has just started rejecting apps that use AMBlurView or MDBlurView.

I have a paid version of my app already approved and it uses this project, but the "lite" version was just reviewed and rejected.  When I did a quick search, there are others complaining of the same thing during the last 6 days.

As a quick fix, I just removed the use of AMBlurView from my project.

**Comment by daviddelmonte** [comment]
Can we still use MYIntroductionView? (also by Matt York)

**Comment by tspinelli** [comment]
Not as it is currently written.  My app does not directly use AMBlurView-I am using this pod (MyBlurIntroductionView).  MyBlurIntroductionView includes AMBlurView and that is how I got rejected.

My "quick" solution was to simply remove AMBlurView from MyBlurIntroductionView and force MyBlurIntroductionView down the pre-iOS7 path.  Because of how I use MyBlurIntroductionView my application looks completely the same and I should get past this check.

**Comment by MatthewYork** [comment]
It is sad to here that Apple did this, but I will work on removing the blur out of MYBlurIntroductionView. I'm swamped right now with other things, but I will work on it when I am free.

@daviddelmonte, you can still use MYIntroductionView, but it is much less stable, so what @tspinelli  recommends is what I would recommend as well.

**Comment by tspinelli** [comment]
@daviddelmonte - My apologies, I read your message wrong and responded thinking you were asking if you could use MyBlurIntroductionView

@MatthewYork If you would like, I can commit my changes to a branch.  I'm not suggesting it is the right way to do it, it was just quick and dirty.  I just got rid of the "blurView" property on the MYBlurIntroductionView object.

**Comment by MatthewYork** [comment]
@tspinelli You know, that's really all I was going to do in the interim as well. Go ahead and commit it up and I will give it a look.

Thank you!

**Comment by MatthewYork** [comment]
@tspinelli has graciously provided us with a revision that removes AMBlurView from the implementation of MYBlurIntroductionView.

I'm going to close this issue and then remove the files, update the podspec, etc
