### ISSUE TITLE
MYBlurIntroductionView <--> MYIntroductionPanel retain cycle!

### ISSUE THREAD

**Issue by maross** [MatthewYork/MYBlurIntroductionView#23]
I noticed that images contained in panels were not deallocated causing memory warning, there is a retain cycle between the container view (MyBlurIntroductionView) and children (MYIntorductionPanel) because the latter have a strong reference with this one. The property should be changed to assign (MyIntorductionPanel.h, line 27).

**Comment by MatthewYork** [comment]
Good catch!
I have changed the introduction view reference to weak in commit 25c8eaf142df3f4bf30b352df47d67163c50e60f. I will issue an updated cocoa pod soon.

Thanks,

-Matt
