### ISSUE TITLE
Dismiss button?

### ISSUE THREAD

**Issue by Alifar** [MatthewYork/MYBlurIntroductionView#27]
Hi there,

Is there some sort of dismiss function which I can add to a button?

Also, how can I let this popup only at the first time someone opens the app?

Thank you for your answers.

Love your work btw :)

**Comment by MatthewYork** [comment]
1) Unfortunately, there is no dismiss button built in. You will have to add that yourself. You can dismiss the view by simply removing it from the superview

2) A cheap way to have the intro only open the first time is to set a boolean in the NSUserDefaults.

``` objc
[[NSUserDefaults standardDefaults] setBool:YES forKey:@"introShown"];
[[NSUserDefaults standardDefaults] synchronize];
```

``` Swift
NSUserDefualts.standardUserDefaults().setBool(true, forKey:"introShown")
NSUserDefaults.standardUserDefaults().synchronize()
```

Then you can just ask for that value in an if statement on every run through. If the value is already set, then you do not need to show the intro again.

``` objc
if (![[NSUserDefaults standardDefaults] boolForKey:@"introShown"]) {
   //show introduction
}

```

``` Swift
let showIntro = (Bool)NSUserDefualts.standardUserDefaults().valueForKey("introShown")
if (showIntro == false) {
   //show introduction
}
```

Thanks for using MYBlurIntroductionView!

-Matt

**Comment by Alifar** [comment]
Hi Matthew,

Thank you for your useful answer.

But still don't know how to code the dismiss when I use the MYCustomPanel as last. Can you please let me know what to add to panelDidDisappear in order to dismiss it when using [self panelDidDisappear] on a button? 

Its not possible to use the skip functionality there?

Thanks!

Op 27 okt. 2014, om 16:03 heeft Matthew York notifications@github.com het volgende geschreven:

**Comment by MatthewYork** [comment]
Every MYCustomPanel has a pointer back to the parent introduction view. What you can do is use this property to remove the parent introduction view from the superview. [parentSuperView removeFromSuperView]. I don't think that will cause any problem
