### ISSUE TITLE
introductionView setBackgroundColor

### ISSUE THREAD

**Issue by shmidt** [MatthewYork/MYBlurIntroductionView#3]
Hi, thanks for sharing!

Trying to set colour for the first screen and it seems to be impossible.
[introductionView setBackgroundColor:[UIColor colorWithRed:0.300 green:0.171 blue:0.686 alpha:1.000]];

Delegate works only after switching screens, so it's not possible to do this either.

**Comment by MatthewYork** [comment]
Thanks for taking a look at my control! I will be looking into both of these things for you, but if you find anything, feel free to initiate a pull request with the fixes.

**Comment by shmidt** [comment]
OK, thanks. I'll try to find it out.

**Comment by shmidt** [comment]
`buildIntroductionWithPanels` rewrote backgroundColor. Need to think a little bit how to handle this.

**Comment by MatthewYork** [comment]
Interesting... If that is where it is occurring, it shouldn't be too bad to fix this.

**Comment by MatthewYork** [comment]
Schmidt,

Took a look at the problem, and I fixed the overwrite problem and removed some bloat along the way. I'm going to close this but let me know if you have more problems.

Thanks,

-Matt
