### ISSUE TITLE
Allow moving to a specific panel

### ISSUE THREAD

**Issue by misterwell** [MatthewYork/MYBlurIntroductionView#5]
The following method is defined but not implemented:

``` Objective-C
-(void)changeToPanelAtIndex:(NSInteger)index
```

Providing this would give users of the library a way to throw a user back to a specific panel if there is some error condition preventing them from continuing.

**Comment by MatthewYork** [comment]
I forgot that I didn't implement that one. I will take a look at it as soon as I can!

**Comment by misterwell** [comment]
I worked on it today and got something working, so I may have a pull request for you tomorrow.

**Comment by MatthewYork** [comment]
Good deal. Remember to test Right-to-Left languages in addition to the default Left-to-Right.

**Comment by misterwell** [comment]
See commit bbc234b503cf3157fefa9cf272c8d570f51da09e
