### ISSUE TITLE
Issue with initWithFrame:(CGRect)frame nibNamed:(NSString *)nibName

### ISSUE THREAD

**Issue by bassrock** [MatthewYork/MYBlurIntroductionView#7]
I am getting an error on line 84 in the MYIntroductionPanel class.

``` obj-c
self.isCustomPanel = YES;
```

It looks like this variable is not getting synthesized properly. I am using the latest version on cocoapods.

**Comment by MatthewYork** [comment]
This cocoapods revision is a bit old, but I will retag and get it updated soon. Apologies.

**Comment by bassrock** [comment]
No problem. Thanks

**Comment by bassrock** [comment]
I tried pulling directly from the repo and have the exact same issue. I am on iOS7 could it be an arc vs. non arc issue?

**Comment by bassrock** [comment]
Wow totally my dumb mistake. I forgot to set the class in my .xib.
